### ISSUE TITLE
bucket name required

### ISSUE THREAD

**Issue by stanim** [budkin/jam#11]
I generated an app password with:
https://security.google.com/settings/security/apppasswords

Unfortunately I am unable to start jam, but i look forward to use it.

$ jam
Email: xxx@gmail.com
Password: ****************
2017/01/28 16:19:17 bucket name required

**Comment by budkin** [comment]
hm. are you using the latest release? is your repo up to date if you are building from source? run it with `-debug` flag and post the output

**Comment by stanim** [comment]
I used "go get -u" to install. Is there a better way?

```
$ go get -u github.com/budkin/jam
$ jam -debug                     
Email: xxx@gmail.com
Password: ****************
panic: bucket name required

goroutine 1 [running]:
panic(0x6bb320, 0xc4200103d0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.checkErr(0xa5af20, 0xc4200103d0)
	/home/stani/Labo/go/src/github.com/budkin/jam/main.go:78 +0xc4
main.refreshLibrary.func1(0xc4202a6700, 0x741c68, 0xc4202a6700)
	/home/stani/Labo/go/src/github.com/budkin/jam/lib.go:94 +0x39b
github.com/budkin/jam/vendor/github.com/boltdb/bolt.(*DB).Update(0xc4201261e0, 0xc4208ede68, 0x0, 0x0)
	/home/stani/Labo/go/src/github.com/budkin/jam/vendor/github.com/boltdb/bolt/db.go:598 +0xb5
main.refreshLibrary()
	/home/stani/Labo/go/src/github.com/budkin/jam/lib.go:118 +0x17a
main.checkCreds()
	/home/stani/Labo/go/src/github.com/budkin/jam/auth.go:58 +0x6e
main.main()
	/home/stani/Labo/go/src/github.com/budkin/jam/main.go:68 +0xb3

```

**Comment by budkin** [comment]
if this isn't fixed after the latest commit reopen the issue

**Comment by stanim** [comment]
Works perfectly! Enjoying my music now. Thanks a lot.
