### ISSUE TITLE
0.6.0.a segfaults

### ISSUE THREAD

**Issue by jc00ke** [budkin/jam#39]
Just tried the latest alpha release and it segfaulted on startup.

```
⋊> ~ jam                                                                                                                                                                              10:18:21
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e15b4]

goroutine 1 [running]:
github.com/budkin/jam/ui.(*App).populatePlaylists.func1(0xc4203300e0, 0x7a4058, 0xc4203300e0)
        /home/budkin/go/src/github.com/budkin/jam/ui/app.go:165 +0x94
github.com/budkin/jam/vendor/github.com/boltdb/bolt.(*DB).View(0xc420128000, 0xc42004be48, 0x0, 0x0)
        /home/budkin/go/src/github.com/budkin/jam/vendor/github.com/boltdb/bolt/db.go:629 +0x9f
github.com/budkin/jam/ui.(*App).populatePlaylists(0xc42021c0a0)
        /home/budkin/go/src/github.com/budkin/jam/ui/app.go:171 +0x8e
github.com/budkin/jam/ui.(*App).Run(0xc42021c0a0)
        /home/budkin/go/src/github.com/budkin/jam/ui/app.go:155 +0x69
main.doUI(0xc4200baea0, 0x0, 0x0, 0x0, 0xc420128000, 0x0, 0x0)
        /home/budkin/go/src/github.com/budkin/jam/main.go:91 +0x8b
main.main()
        /home/budkin/go/src/github.com/budkin/jam/main.go:80 +0x1c0
```

**Comment by budkin** [comment]
Have you tried deleting the database (~/.local/share/jamdb)? some things in the database changed since 0.4.0

**Comment by jc00ke** [comment]
I did, and then it crashed when I tried to synchronize the database.

```
⋊> ~ jam                                                                                                                                                                              13:19:40
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6e1720, 0xc42000c1b0)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/budkin/jam/ui.(*App).hlEntry(0xc420256080)
        /home/budkin/go/src/github.com/budkin/jam/ui/tui.go:72 +0x47c
github.com/budkin/jam/ui.(*App).updateUI(0xc420256080)
        /home/budkin/go/src/github.com/budkin/jam/ui/tui.go:56 +0x45c
github.com/budkin/jam/ui.(*App).mainLoop(0xc420256080)
        /home/budkin/go/src/github.com/budkin/jam/ui/app.go:366 +0xe9
github.com/budkin/jam/ui.(*App).Run(0xc420256080)
        /home/budkin/go/src/github.com/budkin/jam/ui/app.go:154 +0x8b
main.doUI(0xc4200bf080, 0x0, 0x0, 0x0, 0xc420136000, 0x0, 0x0)
        /home/budkin/go/src/github.com/budkin/jam/main.go:91 +0x74
main.main()
        /home/budkin/go/src/github.com/budkin/jam/main.go:80 +0x115
```

**Comment by jc00ke** [comment]
Actually, I take that back.

I removed Kendrick's new `DAMN`, sync'd successfully, then tabbed over to the album/track list and then it crashed.
