### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by DevStorage** [budkin/jam#50]
When in ctrl+space mod trying to search and accidentally pressing / after /
goroutine 1 [running]:
github.com/budkin/jam/ui.(*App).searchQuery(0xc4200a4aa0, 0xc4202495c0, 0x4, 0x4)
	/home/budkin/go/src/github.com/budkin/jam/ui/app.go:273 +0x328
github.com/budkin/jam/ui.(*App).search(0xc4200a4aa0, 0xc4202495c0, 0x4, 0x4)
	/home/budkin/go/src/github.com/budkin/jam/ui/app.go:261 +0x25b
github.com/budkin/jam/ui.(*App).mainLoop(0xc4200a4aa0)
	/home/budkin/go/src/github.com/budkin/jam/ui/app.go:358 +0x37e
github.com/budkin/jam/ui.(*App).Run(0xc4200a4aa0)
	/home/budkin/go/src/github.com/budkin/jam/ui/app.go:158 +0x99
main.doUI(0xc4200d8be0, 0x0, 0x0, 0x0, 0xc420146000, 0x0, 0x0)
	/home/budkin/go/src/github.com/budkin/jam/main.go:91 +0x8b
main.main()
	/home/budkin/go/src/github.com/budkin/jam/main.go:80 +0x1c0

**Comment by budkin** [comment]
to someone wanting to take over this repo: you should to forbid search and shuffling in ctrl+space mode altogether
