### ISSUE TITLE
Error with json

### ISSUE THREAD

**Issue by nlamirault** [budkin/jam#6]
I've got this error : 

```
$ ./jam
Email: xxxxxxxxxx@gmail.com
Password: ***************
2017/01/26 23:13:56 json: cannot unmarshal number 17748 into Go value of type uint8
```

Any idea ?

**Comment by budkin** [comment]
I added a debug flag, so checkErr() invokes panic instead of just logging, so you can see the full stack trace. Try now. I think this error has to do with the types I've "fixed", so 17748 is either a track or disc number

**Comment by nlamirault** [comment]
```
./jam -debug
Email: xxxxxxxx@gmail.com
Password: ***************
panic: json: cannot unmarshal number 17748 into Go value of type uint8

goroutine 1 [running]:
panic(0x6b93e0, 0xc4208b0900)
        /home/nlamirault/Apps/go/src/runtime/panic.go:500 +0x1a1
main.checkErr(0xa59e00, 0xc4208b0900)
        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/main.go:78 +0xc4
main.refreshLibrary()
        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/lib.go:49 +0x67
main.checkCreds()
        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/auth.go:58 +0x6e
main.main()
        /home/nlamirault/Apps/golang/src/github.com/budkin/jam/main.go:68 +0xb3
```

**Comment by budkin** [comment]
May I ask what album on GPM has that many tracks?
