### ISSUE TITLE
Crash on window resize

### ISSUE THREAD

**Issue by MartijnBraam** [budkin/jam#7]
I made the jam window smaller (to 21 lines high) and it crashed with this error:

```go
panic: runtime error: index out of range

goroutine 1 [running]:
main.hlEntry(0xac1000, 0xc420078580)
	/home/budkin/go/src/github.com/budkin/jam/ui.go:391 +0x42c
main.updateUI(0xac1000, 0xc420078580)
	/home/budkin/go/src/github.com/budkin/jam/ui.go:366 +0x3aa
main.mainLoop(0xac1000, 0xc420078580)
	/home/budkin/go/src/github.com/budkin/jam/ui.go:110 +0xef
main.initUI()
	/home/budkin/go/src/github.com/budkin/jam/ui.go:100 +0x122
main.main()
	/home/budkin/go/src/github.com/budkin/jam/main.go:68 +0xb8
```

Starting at that size is fine

**Comment by budkin** [comment]
I assume you're using version 0.1. Please try the same with the latest release, because of the changes in the files I can't track those line numbers

**Comment by MartijnBraam** [comment]
This was with the 0.2 release as far as I know but I can't replicate it now. I do notice that the current highlighted item changes when I resize the window.

**Comment by budkin** [comment]
> I do notice that the current highlighted item changes when I resize the window.

Yeah, that's a problem I need to address, feel free to create another issue. I'll leave this open for now

**Comment by MartijnBraam** [comment]
I had the crash again on my other machine with version 0.3.2

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6c2d60, 0xc42000c190)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/budkin/jam/ui.(*App).makeSongLine(0xc42009f100, 0xc420782000, 0xd0, 0x69cca0)
	/home/budkin/go/src/github.com/budkin/jam/ui/io.go:57 +0x445
github.com/budkin/jam/ui.(*App).printSongs(0xc42009f100, 0x0, 0xc)
	/home/budkin/go/src/github.com/budkin/jam/ui/tui.go:167 +0x57c
github.com/budkin/jam/ui.(*App).updateUI(0xc42009f100)
	/home/budkin/go/src/github.com/budkin/jam/ui/tui.go:46 +0x222
github.com/budkin/jam/ui.(*App).mainLoop(0xc42009f100)
	/home/budkin/go/src/github.com/budkin/jam/ui/app.go:294 +0xd8
github.com/budkin/jam/ui.(*App).Run(0xc42009f100)
	/home/budkin/go/src/github.com/budkin/jam/ui/app.go:143 +0x8b
main.doUI(0xc4204380e0, 0xc420142000, 0xc420142000, 0x0)
	/home/budkin/go/src/github.com/budkin/jam/main.go:87 +0x52
main.main()
	/home/budkin/go/src/github.com/budkin/jam/main.go:76 +0xbc
```

**Comment by budkin** [comment]
Sorry, it took me a while to grasp what the guy on Slack is trying to say
